services:
  db:
    image: postgres:16
    container_name: studycomply_db
    environment:
      POSTGRES_USER: studycomply
      POSTGRES_PASSWORD: studycomply
      POSTGRES_DB: studycomply
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
